"""document tablosu + RLS

Revision ID: 0003_document
Revises: 0002_core_schema
Create Date: 2026-07-03 19:25:39.399532
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_document"
down_revision: str | None = "0002_core_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "ADMINISTRATIVE",
                "TECHNICAL",
                "CONTRACT",
                "ADDENDUM",
                "OTHER",
                name="documentkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_UPLOAD",
                "UPLOADED",
                "FAILED",
                name="documentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organization.id"],
            name=op.f("fk_document_tenant_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tender.id"],
            name=op.f("fk_document_tender_id_tender"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_index(op.f("ix_document_tenant_id"), "document", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_document_tender_id"), "document", ["tender_id"], unique=False)
    # ### end Alembic commands ###

    # --- RLS: kiracı izolasyonu (document kiracı-özeldir; bkz. ADR-0003) ---
    op.execute("ALTER TABLE document ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY document_tenant_isolation ON document "
        "USING (tenant_id = current_setting('app.current_tenant', true)::uuid) "
        "WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS document_tenant_isolation ON document")
    op.drop_index(op.f("ix_document_tender_id"), table_name="document")
    op.drop_index(op.f("ix_document_tenant_id"), table_name="document")
    op.drop_table("document")
    # ### end Alembic commands ###
