/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Kimlik doğrular ve bir JWT erişim token'ı döndürür.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Geçerli token'a karşılık gelen kullanıcıyı döndürür.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Yeni bir organizasyon ve admin kullanıcı oluşturur.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capability-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capability Profile
         * @description Aktif kiracının yetkinlik profilini döndürür (yoksa 404).
         */
        get: operations["get_capability_profile_api_v1_capability_profile_get"];
        put?: never;
        /**
         * Upsert Capability Profile
         * @description Aktif kiracının yetkinlik profilini oluşturur veya günceller (upsert).
         *
         *     Kiracı başına tek profil olduğundan atomik ``INSERT ... ON CONFLICT DO UPDATE``
         *     kullanılır. Böylece profili olmayan iki EŞZAMANLI istek de ``uq_capability_
         *     profile_tenant`` ihlaliyle 500 üretmez — ikisi de başarılı olur (RLS WITH CHECK
         *     sağlanır: ``tenant_id`` değişmez, aktif kiracıya eşittir).
         */
        post: operations["upsert_capability_profile_api_v1_capability_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance-results/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Compliance Result
         * @description Uygunluk değerlendirmesini onaylar/reddeder/geri alır veya düzeltir (AuditLog'lu).
         */
        patch: operations["patch_compliance_result_api_v1_compliance_results__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/deliverables/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Deliverable
         * @description İstenen belgeyi onaylar/reddeder/geri alır veya içeriğini düzeltir (AuditLog'lu).
         */
        patch: operations["patch_deliverable_api_v1_deliverables__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/documents/{document_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Yüklemeyi doğrular, dokümanı ``uploaded`` yapar ve işleme job'ını kuyruklar.
         *
         *     Idempotent: zaten ``uploaded`` bir doküman için mevcut son iş döndürülür.
         *     Kiracı bağlamı elle kurulur; job kuyruklama commit SONRASI yapılır (worker'ın
         *     henüz görünmeyen bir satırı okuma yarışını önler).
         */
        post: operations["complete_upload_api_v1_documents__document_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document File
         * @description İnceleme ekranı doküman önizlemesi için imzalı GET URL'i döndürür.
         *
         *     URL süre-sınırlıdır (varsayılan 1 saat); erişim RLS ile kiracıya kapalıdır
         *     (başka kiracının dokümanı 404). Yüklemesi tamamlanmamış doküman için 409.
         */
        get: operations["get_document_file_api_v1_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{kind}/{finding_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Finding Comments
         * @description Bulgunun ekip yorumlarını eskiden-yeniye listeler.
         */
        get: operations["list_finding_comments_api_v1_findings__kind___finding_id__comments_get"];
        put?: never;
        /**
         * Create Finding Comment
         * @description Bulguya ekip notu düşer (temel işbirliği; AuditLog'lu).
         */
        post: operations["create_finding_comment_api_v1_findings__kind___finding_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{kind}/{finding_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Finding History
         * @description Bulgunun düzenleme geçmişini (AuditLog) yeniden-eskiye listeler.
         */
        get: operations["list_finding_history_api_v1_findings__kind___finding_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Tek bir işin durumunu döndürür (RLS: başka kiracınınki 404).
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description ``failed`` bir işi yeniden kuyruklar (``failed → queued``, §5.5).
         *
         *     Kuyruklama commit SONRASI yapılır (worker'ın görünmeyen satırı okuma yarışı
         *     yok); ``attempts`` sıfırlanmaz — toplam deneme geçmişi korunur.
         */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requirements/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Requirement
         * @description Gereksinimi onaylar/reddeder/geri alır veya içeriğini düzeltir (AuditLog'lu).
         */
        patch: operations["patch_requirement_api_v1_requirements__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/risks/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Risk
         * @description Risk maddesini onaylar/reddeder/geri alır veya içeriğini düzeltir (AuditLog'lu).
         */
        patch: operations["patch_risk_api_v1_risks__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Servis adı, sürümü ve çalışma ortamını döndürür.
         */
        get: operations["version_api_v1_system_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenders
         * @description Aktif kiracının ihalelerini listeler (RLS ile filtrelenir).
         */
        get: operations["list_tenders_api_v1_tenders_get"];
        put?: never;
        /**
         * Create Tender
         * @description Aktif kiracı için yeni bir ihale projesi oluşturur.
         */
        post: operations["create_tender_api_v1_tenders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender
         * @description Tek bir ihaleyi döndürür (RLS: başka kiracınınki 404).
         */
        get: operations["get_tender_api_v1_tenders__tender_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Compliance
         * @description İhalenin gereksinim ↔ yetkinlik profili değerlendirmelerini listeler.
         *
         *     Yalnız bir ``CapabilityProfile`` tanımlıysa üretilir. Grounding sözleşmesi
         *     ``list_requirements`` ile aynıdır: değerlendirme, değerlendirilen gereksinimin
         *     kaynak maddesine bağlıdır (kaynaksız dönmez).
         */
        get: operations["list_compliance_api_v1_tenders__tender_id__compliance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Deliverables
         * @description İhalenin çıkarılmış istenen belgelerini kaynaklarıyla listeler.
         *
         *     Grounding sözleşmesi ``list_requirements`` ile aynıdır (kaynaksız dönmez).
         */
        get: operations["list_deliverables_api_v1_tenders__tender_id__deliverables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Bir ihaleye bağlı dokümanları listeler.
         */
        get: operations["list_documents_api_v1_tenders__tender_id__documents_get"];
        put?: never;
        /**
         * Create Document
         * @description Bir ihaleye doküman kaydı açar ve imzalı yükleme URL'i döndürür.
         *
         *     ``Idempotency-Key`` başlığı verilirse aynı anahtarla tekrarlanan istek yeni
         *     kayıt açmaz; mevcut kaydı taze bir imzalı URL ile döndürür.
         */
        post: operations["create_document_api_v1_tenders__tender_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Tender
         * @description Onaylı analizden yapılandırılmış Word/Excel raporu üretir ve indirir.
         *
         *     Hiç rapora girecek bulgu yoksa 409 döner (önce inceleme/onay gerekir).
         *     Export AuditLog'a yazılır (kim-ne zaman-hangi biçim, §10.5).
         */
        post: operations["export_tender_api_v1_tenders__tender_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/findings/bulk-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Review
         * @description Seçili bulguları tek transaction'da toplu onaylar/reddeder (AuditLog'lu).
         *
         *     Başka ihaleye/kiracıya ait ya da var olmayan id'ler ``skipped``a düşer.
         *     Toplu onayda EDITED satırlar ``unchanged`` sayılır (düzeltilmiş hâl onaylı
         *     sayılır; toplu işlem "düzeltildi" izini ezmez).
         */
        post: operations["bulk_review_api_v1_tenders__tender_id__findings_bulk_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requirements
         * @description İhalenin çıkarılmış gereksinimlerini kaynaklarıyla listeler.
         *
         *     Zorunlu grounding (ADR-0006): kaynak ``ParsedElement``e bağlanamayan bulgu
         *     bu uçtan DÖNMEZ — inner join kaynaksız satırı yapısal olarak dışarıda bırakır.
         */
        get: operations["list_requirements_api_v1_tenders__tender_id__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Risks
         * @description İhalenin çıkarılmış risk maddelerini kaynaklarıyla listeler.
         *
         *     Grounding sözleşmesi ``list_requirements`` ile aynıdır (kaynaksız dönmez).
         */
        get: operations["list_risks_api_v1_tenders__tender_id__risks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Timeline
         * @description İhalenin çıkarılmış tarih/süre öğelerini kaynaklarıyla listeler.
         *
         *     Grounding sözleşmesi ``list_requirements`` ile aynıdır (kaynaksız dönmez).
         */
        get: operations["list_timeline_api_v1_tenders__tender_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timeline-events/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Timeline Event
         * @description Takvim öğesini onaylar/reddeder/geri alır veya içeriğini düzeltir (AuditLog'lu).
         */
        patch: operations["patch_timeline_event_api_v1_timeline_events__finding_id__patch"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness — süreç ayakta mı (bağımlılık kontrol etmez).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness — DB ve Redis erişilebilir mi; değilse 503 döner.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BulkReviewAction
         * @description Toplu inceleme eylemi (yalnız onay/red — geri alma tekildir).
         * @enum {string}
         */
        BulkReviewAction: "approve" | "reject";
        /**
         * BulkReviewItem
         * @description Toplu istekte tek bulgu adresi.
         */
        BulkReviewItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["FindingKind"];
        };
        /**
         * BulkReviewRequest
         * @description Toplu onay/red isteği.
         */
        BulkReviewRequest: {
            action: components["schemas"]["BulkReviewAction"];
            /** Items */
            items: components["schemas"]["BulkReviewItem"][];
        };
        /**
         * BulkReviewResponse
         * @description Toplu işlem sonucu: değişen / zaten hedefte / bulunamayan.
         */
        BulkReviewResponse: {
            /** Skipped */
            skipped: string[];
            /** Unchanged */
            unchanged: number;
            /** Updated */
            updated: number;
        };
        /**
         * CapabilityProfileResponse
         * @description Kiracının yetkinlik profili.
         */
        CapabilityProfileResponse: {
            /** Content */
            content: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * CapabilityProfileUpsert
         * @description Yetkinlik profili girişi (serbest metin).
         */
        CapabilityProfileUpsert: {
            /** Content */
            content: string;
        };
        /**
         * ComplianceResultPatch
         * @description Uygunluk değerlendirmesi düzeltme alanları (durum + gerekçe).
         */
        ComplianceResultPatch: {
            action?: components["schemas"]["ReviewAction"] | null;
            /** Rationale */
            rationale?: string | null;
            status?: components["schemas"]["ComplianceStatus"] | null;
        };
        /**
         * ComplianceResultResponse
         * @description Gereksinim ↔ yetkinlik profili değerlendirmesi (kaynaklı).
         */
        ComplianceResultResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rationale */
            rationale: string;
            /** Requirement Text */
            requirement_text: string;
            review: components["schemas"]["FindingReview"];
            source: components["schemas"]["FindingSource"];
            status: components["schemas"]["ComplianceStatus"];
        };
        /**
         * ComplianceStatus
         * @description Gereksinimin firma yetkinlik profiline göre karşılanma durumu (§6.7).
         * @enum {string}
         */
        ComplianceStatus: "met" | "partial" | "unmet";
        /**
         * DeliverableKind
         * @description Sunulacak belge tipi (§8.1 ``Deliverable``).
         * @enum {string}
         */
        DeliverableKind: "document" | "certificate" | "guarantee" | "other";
        /**
         * DeliverablePatch
         * @description İstenen belge düzeltme alanları.
         */
        DeliverablePatch: {
            action?: components["schemas"]["ReviewAction"] | null;
            /** Is Mandatory */
            is_mandatory?: boolean | null;
            kind?: components["schemas"]["DeliverableKind"] | null;
            /** Name */
            name?: string | null;
        };
        /**
         * DeliverableResponse
         * @description Çıkarılmış istenen belge (kaynaklı).
         */
        DeliverableResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Mandatory */
            is_mandatory: boolean;
            kind: components["schemas"]["DeliverableKind"];
            /** Name */
            name: string;
            review: components["schemas"]["FindingReview"];
            source: components["schemas"]["FindingSource"];
        };
        /**
         * DocumentCompleteResponse
         * @description Tamamlanan yükleme: güncel doküman + kuyruğa alınan iş.
         */
        DocumentCompleteResponse: {
            document: components["schemas"]["DocumentResponse"];
            job: components["schemas"]["JobResponse"] | null;
        };
        /**
         * DocumentCreate
         * @description Yeni doküman kaydı (imzalı yükleme URL'i döner).
         */
        DocumentCreate: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /** @default other */
            kind: components["schemas"]["DocumentKind"];
        };
        /**
         * DocumentFileResponse
         * @description Önizleme için süre-sınırlı imzalı indirme URL'i (Sprint 3.1, §4.2).
         */
        DocumentFileResponse: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /** Url */
            url: string;
        };
        /**
         * DocumentKind
         * @description İhale dosyası türü.
         * @enum {string}
         */
        DocumentKind: "administrative" | "technical" | "contract" | "addendum" | "other";
        /**
         * DocumentResponse
         * @description Doküman özeti.
         */
        DocumentResponse: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["DocumentKind"];
            /** Size Bytes */
            size_bytes: number | null;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Tender Id
             * Format: uuid
             */
            tender_id: string;
        };
        /**
         * DocumentStatus
         * @description Dosyanın yükleme/işleme durumu.
         * @enum {string}
         */
        DocumentStatus: "pending_upload" | "uploaded" | "failed";
        /**
         * DocumentUploadResponse
         * @description Doküman kaydı + süre-sınırlı imzalı yükleme URL'i.
         */
        DocumentUploadResponse: {
            document: components["schemas"]["DocumentResponse"];
            /** Storage Key */
            storage_key: string;
            /** Upload Url */
            upload_url: string;
        };
        /**
         * Environment
         * @description Çalışma ortamları.
         * @enum {string}
         */
        Environment: "development" | "staging" | "production";
        /**
         * ExportFormat
         * @description Export dosya biçimi.
         * @enum {string}
         */
        ExportFormat: "docx" | "xlsx";
        /**
         * FindingCommentCreate
         * @description Yeni bulgu yorumu.
         */
        FindingCommentCreate: {
            /** Body */
            body: string;
        };
        /**
         * FindingCommentResponse
         * @description Tek bulgu yorumu.
         */
        FindingCommentResponse: {
            /** Author User Id */
            author_user_id: string | null;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            finding_kind: components["schemas"]["FindingKind"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * FindingHistoryEntry
         * @description Bulgu üzerindeki tek denetim kaydı (düzenleme geçmişi satırı).
         */
        FindingHistoryEntry: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * FindingKind
         * @description Bulgu koleksiyonlarının ortak adresleme anahtarı (yorum/geçmiş uçları).
         *
         *     Değerler AuditLog ``resource_type`` alanında ve API yollarında kullanılır;
         *     inceleme UI'sindeki beş sekmeyle birebir eşleşir.
         * @enum {string}
         */
        FindingKind: "requirement" | "deliverable" | "risk" | "timeline" | "compliance";
        /**
         * FindingReview
         * @description Bulgunun insan-döngüde inceleme durumu (Sprint 3.2, §4.3).
         */
        FindingReview: {
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            status: components["schemas"]["ReviewStatus"];
        };
        /**
         * FindingSource
         * @description Bulgunun kaynak konumu — citation zinciri: öğe → sayfa + bbox (§6.9).
         *
         *     Kaynağa bağlanamayan bulgu API'den hiç dönmediği için (ADR-0006) tüm
         *     alanlar kaynak öğeden doludur; bbox yalnız konumsuz formatlarda (DOCX/XLSX)
         *     boştur.
         */
        FindingSource: {
            /** Bbox X0 */
            bbox_x0: number | null;
            /** Bbox X1 */
            bbox_x1: number | null;
            /** Bbox Y0 */
            bbox_y0: number | null;
            /** Bbox Y1 */
            bbox_y1: number | null;
            /**
             * Element Id
             * Format: uuid
             */
            element_id: string;
            /** Element Seq */
            element_seq: number;
            /** Page */
            page: number;
            /** Quote */
            quote: string;
            resolution: components["schemas"]["GroundingResolution"];
            /** Section */
            section: string | null;
        };
        /**
         * GroundingResolution
         * @description Bulgunun kaynağa bağlanma düzeyi (§6.9, ADR-0006).
         * @enum {string}
         */
        GroundingResolution: "element" | "chunk" | "ungrounded";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness yanıtı.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * JobResponse
         * @description İşleme işinin durumu.
         */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Error Message */
            error_message: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobStatus
         * @description İşleme işinin durumu (§5.5).
         * @enum {string}
         */
        JobStatus: "queued" | "parsing" | "indexing" | "extracting" | "review_ready" | "failed";
        /**
         * LoginRequest
         * @description E-posta/parola ile giriş.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ReadinessComponent
         * @description Tek bir bağımlılığın (DB, Redis) hazırlık durumu.
         */
        ReadinessComponent: {
            /** Detail */
            detail?: string | null;
            /** Healthy */
            healthy: boolean;
            /** Name */
            name: string;
        };
        /**
         * ReadinessResponse
         * @description Readiness yanıtı — bağımlılık kontrol sonuçları.
         */
        ReadinessResponse: {
            /** Components */
            components: components["schemas"]["ReadinessComponent"][];
            /** Ready */
            ready: boolean;
        };
        /**
         * RegisterRequest
         * @description Yeni organizasyon + admin kullanıcı kaydı.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Org Name */
            org_name: string;
            /** Org Slug */
            org_slug: string;
            /** Password */
            password: string;
        };
        /**
         * RequirementKind
         * @description Gereksinim tipi (§8.1 ``Requirement``).
         * @enum {string}
         */
        RequirementKind: "technical" | "administrative" | "financial";
        /**
         * RequirementPatch
         * @description Gereksinim düzeltme alanları.
         */
        RequirementPatch: {
            action?: components["schemas"]["ReviewAction"] | null;
            /** Is Mandatory */
            is_mandatory?: boolean | null;
            kind?: components["schemas"]["RequirementKind"] | null;
            /** Text */
            text?: string | null;
        };
        /**
         * RequirementResponse
         * @description Çıkarılmış gereksinim (kaynaklı).
         */
        RequirementResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Mandatory */
            is_mandatory: boolean;
            kind: components["schemas"]["RequirementKind"];
            review: components["schemas"]["FindingReview"];
            source: components["schemas"]["FindingSource"];
            /** Text */
            text: string;
        };
        /**
         * ReviewAction
         * @description Tek bulgu üzerinde inceleme eylemi.
         * @enum {string}
         */
        ReviewAction: "approve" | "reject" | "reset";
        /**
         * ReviewStatus
         * @description Bulgunun insan-döngüde inceleme durumu (Sprint 3.2, §4.3).
         *
         *     Çıkarım sonrası her bulgu PENDING doğar; insan onaylar, düzeltir (içerik
         *     değişikliği) veya reddeder. EDITED onaylı sayılır (düzeltilmiş hâliyle);
         *     REJECTED bulgular export'a girmez. Yeniden çıkarım (delete+insert) inceleme
         *     durumunu bilinçli sıfırlar — yeni çıkarım yeni inceleme gerektirir.
         * @enum {string}
         */
        ReviewStatus: "pending" | "approved" | "edited" | "rejected";
        /**
         * RiskCategory
         * @description Risk maddesinin türü (TR ihale alanı; getirim şablonlarıyla hizalı).
         * @enum {string}
         */
        RiskCategory: "penalty" | "termination" | "warranty" | "payment" | "other";
        /**
         * RiskPatch
         * @description Risk maddesi düzeltme alanları.
         */
        RiskPatch: {
            action?: components["schemas"]["ReviewAction"] | null;
            category?: components["schemas"]["RiskCategory"] | null;
            severity?: components["schemas"]["RiskSeverity"] | null;
            /** Text */
            text?: string | null;
        };
        /**
         * RiskResponse
         * @description Çıkarılmış risk maddesi (kaynaklı).
         */
        RiskResponse: {
            category: components["schemas"]["RiskCategory"];
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            review: components["schemas"]["FindingReview"];
            severity: components["schemas"]["RiskSeverity"];
            source: components["schemas"]["FindingSource"];
            /** Text */
            text: string;
        };
        /**
         * RiskSeverity
         * @description Risk maddesinin önem derecesi (Sprint 2.3, §8.2 ``RiskFlag``).
         * @enum {string}
         */
        RiskSeverity: "low" | "medium" | "high";
        /**
         * Role
         * @description RBAC rolleri.
         * @enum {string}
         */
        Role: "admin" | "member" | "viewer";
        /**
         * TenderCreate
         * @description Yeni ihale projesi.
         */
        TenderCreate: {
            /** Title */
            title: string;
        };
        /**
         * TenderExportRequest
         * @description Export isteği: biçim + onay bekleyenler dahil mi.
         */
        TenderExportRequest: {
            /** @default docx */
            format: components["schemas"]["ExportFormat"];
            /**
             * Include Pending
             * @default false
             */
            include_pending: boolean;
        };
        /**
         * TenderResponse
         * @description İhale özeti.
         */
        TenderResponse: {
            /** Created By */
            created_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["TenderStatus"];
            /** Title */
            title: string;
        };
        /**
         * TenderStatus
         * @description İhale analiz durumu.
         * @enum {string}
         */
        TenderStatus: "draft" | "analyzing" | "review_ready" | "archived";
        /**
         * TimelineEventPatch
         * @description Takvim öğesi düzeltme alanları.
         */
        TimelineEventPatch: {
            action?: components["schemas"]["ReviewAction"] | null;
            kind?: components["schemas"]["TimelineKind"] | null;
            /** Label */
            label?: string | null;
            /** Value Text */
            value_text?: string | null;
        };
        /**
         * TimelineEventResponse
         * @description Çıkarılmış tarih/süre öğesi (kaynaklı).
         */
        TimelineEventResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["TimelineKind"];
            /** Label */
            label: string;
            review: components["schemas"]["FindingReview"];
            source: components["schemas"]["FindingSource"];
            /** Value Text */
            value_text: string;
        };
        /**
         * TimelineKind
         * @description Takvim öğesinin türü (Sprint 2.3, §8.2 ``TimelineEvent``).
         * @enum {string}
         */
        TimelineKind: "tender_date" | "bid_deadline" | "delivery" | "warranty" | "other";
        /**
         * TokenResponse
         * @description JWT erişim token'ı.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserResponse
         * @description Kullanıcı + aktif kiracı + rol.
         */
        UserResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["Role"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Servis sürüm/ortam bilgisi.
         */
        VersionResponse: {
            environment: components["schemas"]["Environment"];
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capability_profile_api_v1_capability_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_capability_profile_api_v1_capability_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_compliance_result_api_v1_compliance_results__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplianceResultPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_deliverable_api_v1_deliverables__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliverablePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_documents__document_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_file_api_v1_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_finding_comments_api_v1_findings__kind___finding_id__comments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: components["schemas"]["FindingKind"];
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingCommentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_finding_comment_api_v1_findings__kind___finding_id__comments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: components["schemas"]["FindingKind"];
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingCommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingCommentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_finding_history_api_v1_findings__kind___finding_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: components["schemas"]["FindingKind"];
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_requirement_api_v1_requirements__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_risk_api_v1_risks__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_v1_system_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    list_tenders_api_v1_tenders_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tender_api_v1_tenders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_api_v1_tenders__tender_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_compliance_api_v1_tenders__tender_id__compliance_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceResultResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliverables_api_v1_tenders__tender_id__deliverables_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_tenders__tender_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_tenders__tender_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_tender_api_v1_tenders__tender_id__export_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenderExportRequest"];
            };
        };
        responses: {
            /** @description Üretilen rapor dosyası (Content-Disposition: attachment). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_review_api_v1_tenders__tender_id__findings_bulk_review_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requirements_api_v1_tenders__tender_id__requirements_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_risks_api_v1_tenders__tender_id__risks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_timeline_api_v1_tenders__tender_id__timeline_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_timeline_event_api_v1_timeline_events__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimelineEventPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
